### ISSUE TITLE
https://github.com/StellarSand/IYPS/issues/4#issue-1154919750

### ISSUE THREAD

**Issue by ahma905dsy** [StellarSand/IYPS#15]
### Description
A clear and concise description of what the - [ ] bug is
> 

### Steps to reproduce the behaviour
2. Tap on '....'
3. See error

### Screenshots/error messages (optional)
If applicable, add screenshots or error messages to help explain the issue.

### Additional context (optional)
Any other relevant information or context that can help us understand the issue.

**Comment by StellarSand** [comment]
spam
