### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by mdksec** [StellarSand/IYPS#16]
I hope this message finds you well. I recently had the opportunity to review your app and I am really impressed with the work you are doing. However, I noticed that there is no Turkish language support and I wanted to create a Turkish translation file to address this deficiency. good luck

[strings.xml.txt](https://github.com/StellarSand/IYPS/files/13399892/strings.xml.txt)

**Comment by mdksec** [comment]
> Hello, appreciate the translations. Please also translate the [feedback strings](https://github.com/StellarSand/IYPS/blob/main/app/src/main/res/raw/messages_en.properties) or else the `warnings` & `suggestions` will be shown in English.

done. 

[messages_tr.properties.txt](https://github.com/StellarSand/IYPS/files/13417464/messages_tr.properties.txt)

**Comment by StellarSand** [comment]
Thanks a lot. :+1: 
Changes will be reflected in the next release.
