### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by thestablelover** [StellarSand/IYPS#18]
I've observed issues with the alterations made in the translation. Firstly, I've noticed that the characters ð = \u00F0, þ = \u00FE, ý = \u00FD have been introduced. These characters do not exist in Turkish. Are they mandatory? The inclusion of these unfamiliar characters is negatively impacting the overall appearance of the sentence.

Secondly, the translated text falls short of the anticipated break time. For instance, I initially wrote "3 saniye" as the translation, but an additional character 's' is appended, resulting in "3 saniyes." This is incorrect. Additionally, the part above it, pertaining to "guesses/second," appears to remain untranslated.

These corrupted texts are present in the properties file. Despite making a few modifications to the strings, I'm uncertain about how to address the mentioned issues. As indicated, these problematic characters are embedded in the text within the .properties file.

I also made some minor changes  [strings.xml.txt](https://github.com/StellarSand/IYPS/files/13461579/strings.xml.txt)

**Comment by mdksec** [comment]
![markup_1000004878.png](https://github.com/StellarSand/IYPS/assets/75412448/79015711-ee6b-4a25-ae07-a2d157e90ef0)

**Comment by StellarSand** [comment]
- > the characters ð = \u00F0, þ = \u00FE, ý = \u00FD have been introduced. These characters do not exist in Turkish

    They are already included in the `messages_tr.properties` translations you made [earlier](https://github.com/StellarSand/IYPS/issues/16#issuecomment-1819456352). At least that's what I see on my end. I just made sure they are encoded properly. If it's some other character please ensure proper encoding for it. You can use websites like [Compart](https://www.compart.com/en/unicode), [Symbl](https://symbl.cc/en/unicode/table/) or something else. Example: `ç` would be shown as `U+00E7` on these websites, so just convert it to `\u00E7` for the android strings.

- > "guesses/second," appears to remain untranslated.

    Yeah I have the "guesses/second" as non translatable strings so they aren't translated in any language. Wasn't a good idea. Will fix it in next release.

- > I initially wrote "3 saniye" as the translation, but an additional character 's' is appended, resulting in "3 saniyes."

    Thanks for bringing this to my attention. The issue is that  I've tried to [detect (line 104-122)](https://github.com/StellarSand/IYPS/blob/main/app/src/main/java/com/iyps/utils/UiUtils.kt#L104) when it returns `second`, `hour`, `day` etc. in English and then they are translated in respective locales. In English it'll be `1 second`, `3 seconds` etc, so in other languages it replaces the `second` with the local translation but the last `s` remains as it is when it's plural. Probably other languages are getting incorrectly translated too. Will need to look into it.


<br> Also, please use the [pull request feature](https://github.com/StellarSand/IYPS/pulls) instead of attaching files in the issues section.
Here's the Turkish [primary](https://github.com/StellarSand/IYPS/blob/main/app/src/main/res/values-tr/strings.xml) and [feedback](https://github.com/StellarSand/IYPS/blob/main/app/src/main/res/raw/messages_tr.properties) strings.

**Comment by StellarSand** [comment]
Done. ✔️

Feel free to review and make necessary changes, if any.
Here are the Turkish [primary](https://github.com/StellarSand/IYPS/blob/main/app/src/main/res/values-tr/strings.xml) & [feedback](https://github.com/StellarSand/IYPS/blob/main/app/src/main/res/raw/messages_tr.properties) strings.

<img src="https://github.com/StellarSand/IYPS/assets/68168200/16c3846a-3929-4503-a8f8-b3caaa83a053" width="300"/>  <img src="https://github.com/StellarSand/IYPS/assets/68168200/361e7364-ec77-497a-b597-8987a9a22a85" width="300"/>

**Comment by thestablelover** [comment]
> Done. ✔️
> 
> Feel free to review and make necessary changes, if any. Here are the Turkish [primary](https://github.com/StellarSand/IYPS/blob/main/app/src/main/res/values-tr/strings.xml) & [feedback](https://github.com/StellarSand/IYPS/blob/main/app/src/main/res/raw/messages_tr.properties) strings.
> 
> <img alt="" width="300" src="https://private-user-images.githubusercontent.com/68168200/290557473-16c3846a-3929-4503-a8f8-b3caaa83a053.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1Nzc0NDQsIm5iZiI6MTcwMjU3NzE0NCwicGF0aCI6Ii82ODE2ODIwMC8yOTA1NTc0NzMtMTZjMzg0NmEtMzkyOS00NTAzLWE4ZjgtYjNjYWFhODNhMDUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDE4MDU0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5ZmM4MDFmMzYyNDVlZWFlMzIyYjdiYWRkODU3YTU2ZjkxYmQ5ODQ1ODM2NzIyOGM3NzVmMmY3MDc2NGRkOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ePcbsgnCSESgPOFaS9P5BoIEa3zskvejV6qdjmV_cI0"> <img alt="" width="300" src="https://private-user-images.githubusercontent.com/68168200/290559212-361e7364-ec77-497a-b597-8987a9a22a85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1Nzc0NDQsIm5iZiI6MTcwMjU3NzE0NCwicGF0aCI6Ii82ODE2ODIwMC8yOTA1NTkyMTItMzYxZTczNjQtZWM3Ny00OTdhLWI1OTctODk4N2E5YTIyYTg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDE4MDU0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2YWNkNTQyYzQ1NTM3Y2ZmZTcyNmE2Y2FkMzU5ZTQxODAwNzYyZmY1Y2Q0N2E2MmUwZmRlMjJlMGRjODZiYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FLECmSIVf9aReVj6WdusRyJq5o1mMK5KGHEHkCxOgFg">

This looks absolutely great. I am truly grateful for your effort. Thank you so much for your hard work!
