### ISSUE TITLE
Request to adapt to Chinese

### ISSUE THREAD

**Issue by djs326** [StellarSand/IYPS#19]

**Comment by StellarSand** [comment]
Done. :heavy_check_mark: 

Feel free to review and make necessary changes, if any.
Here are the Chinese [primary](https://github.com/StellarSand/IYPS/blob/main/app/src/main/res/values-zh/strings.xml) & [feedback](https://github.com/StellarSand/IYPS/blob/main/app/src/main/res/raw/messages_zh.properties) strings.

**Comment by djs326** [comment]
This is ok, please update yours.
