### ISSUE TITLE
A little mistake

### ISSUE THREAD

**Issue by my269yf** [StellarSand/IYPS#26]
100 times per minute guess is slower than 10 times per minute guess. It's a logical mistake. I only saw this problem while using Chinese language. I don't know what will happen if I change it into English. I guess it's a translation mistake.
![Screenshot_2024_1202_161806.png](https://github.com/user-attachments/assets/f7504c52-2e28-4653-9cd4-5d8a8566d201)

**Comment by StellarSand** [comment]
There's no `10 guesses/minute` or `100 guesses/minute`.
There is however `10 guesses/second` and `100 guesses/hour`, and `100 guesses/hour` is slower than `10 guesses/second`.

I'd appreciate if you could take a look at [line 37](https://github.com/StellarSand/IYPS/blob/main/app/src/main/res/values-zh/strings.xml#L37) & [line 38](https://github.com/StellarSand/IYPS/blob/main/app/src/main/res/values-zh/strings.xml#L38) in the [Chinese translation](https://github.com/StellarSand/IYPS/blob/main/app/src/main/res/values-zh/strings.xml).

**Comment by StellarSand** [comment]
Probably fixed by [this commit](https://github.com/StellarSand/IYPS/commit/2a735be802df21ad759c51e300cd843541093a2c).
